/** Web paths re-encoded from full-colour masters (tools/import-masters.mjs): each has an .avif beside the .webp. */
export const AVIF_SOURCES = new Set<string>([
  "/about/portrait.webp",
  "/work/bengal-t20/01.webp",
  "/work/bengal-t20/02.webp",
  "/work/bengal-t20/03.webp",
  "/work/bengal-t20/04.webp",
  "/work/bengal-t20/05.webp",
  "/work/bengal-t20/06.webp",
  "/work/house-of-hex/02.webp",
  "/work/house-of-hex/03.webp",
  "/work/house-of-hex/04.webp",
  "/work/indo-thai/02.webp",
  "/work/indo-thai/03.webp",
  "/work/indo-thai/04.webp",
  "/work/jsw-sports/01.webp",
  "/work/jsw-sports/02.webp",
  "/work/jsw-sports/03.webp",
  "/work/jsw-sports/04.webp",
  "/work/jsw-sports/05.webp",
  "/work/jsw-sports/06.webp",
  "/work/mitooshi/01.webp",
  "/work/mitooshi/02.webp",
  "/work/shunya/02.webp",
  "/work/shunya/03.webp",
  "/work/shunya/04.webp",
  "/work/shunya/05.webp",
  "/work/sonde/01.webp",
  "/work/sonde/02.webp",
  "/work/sonde/03.webp",
  "/work/sonde/04.webp",
  "/work/sonde/05.webp",
  "/work/sonde/06.webp",
  "/work/sook/01.webp",
  "/work/sook/02.webp",
  "/work/sook/03.webp",
  "/work/sook/04.webp",
  "/work/sook/05.webp",
  "/work/sook/06.webp",
  "/work/too-yumm/01.webp",
  "/work/too-yumm/02.webp",
  "/work/too-yumm/03.webp",
  "/work/too-yumm/04.webp",
  "/work/too-yumm/05.webp",
  "/work/too-yumm/06.webp"
]);

/** The .avif twin of a web path, when a master exists for it. */
export const avifFor = (src: string) => (AVIF_SOURCES.has(src) ? src.replace(/\.webp$/, '.avif') : null);
