import type { UvNote, Work } from '@/lib/types';

/**
 * Corrections over the Framer import (imported.ts is regenerated by tools/import-framer.mjs, so
 * hand fixes live here). Every value below is the live site's, or Vish's own approved wording.
 */

/** The live site's two discipline tags per project, verbatim. */
export const DISCIPLINES: Record<string, [string, string]> = {
  'too-yumm': ['Packaging Design', '3D Rendering'],
  mitooshi: ['Web Design', 'Creative Direction'],
  'bengal-t20': ['Brand Identity', 'Creative Direction'],
  'house-of-hex': ['Web Design', 'Creative Direction'],
  'indo-thai': ['Web Design', '3D Rendering'],
  shunya: ['Packaging Design', 'Brand Identity'],
  sonde: ['Product Design', 'UI/UX'],
  sook: ['Packaging Design', 'Branding'],
  'jsw-sports': ['Editorial Design', 'Publication Design'],
};

/**
 * Client type. House of Hex, Bengal T20 League and JSW Sports were done as an employee at House of
 * Hex; Too Yumm, SOOK and Indo Thai at The Graphē; Mitooshi during the BHONG internship.
 */
export const CLIENT_TYPE: Record<string, string> = {
  'house-of-hex': 'Studio',
  'bengal-t20': 'Studio',
  'jsw-sports': 'Studio',
  'too-yumm': 'Studio',
  sook: 'Studio',
  'indo-thai': 'Studio',
  mitooshi: 'Studio',
  sonde: 'Self-initiated',
  shunya: 'Self-initiated',
};

/** Outbound link buttons: these four projects only. */
export const LINKS: Record<string, { label: string; href: string }> = {
  mitooshi: { label: 'Live site', href: 'https://www.mitooshi.com/' },
  sonde: { label: 'Full case study', href: 'https://www.behance.net/gallery/256515787/Sonde-Product-Design-Case-Study' },
  'house-of-hex': { label: 'Live site', href: 'https://www.houseofhex.design/' },
  'indo-thai': { label: 'Live site', href: 'https://www.indothai.in/' },
};

export const YEAR: Record<string, number> = { 'house-of-hex': 2026 };

/** Copy fixes, applied to every string of a project (description, sections, alt text). */
const TEXT_FIXES: [RegExp, string][] = [
  [
    /green for the tea-forward flavor, orange for the achari cashews, and so on down the line/g,
    'peach for the coffee almonds, green for the achaari cashews, red for the Thai sweet chilli peanuts, and so on down the line',
  ],
  [/while working the Graphē/g, 'while working at The Graphē'],
  [/Bengal Pro T20 League/g, 'Bengal T20 League'],
];
export const fixText = (s: string) => TEXT_FIXES.reduce((acc, [re, to]) => acc.replace(re, to), s);

/**
 * UV notes, approved by Vish: condensed from his own published case copy. These and only these.
 * Anchors are object-local metres (origin at the base centre); `proof` places the same note on the
 * project's first proof image (uv 0–1 from the top left).
 */
type Note = UvNote & { proof: [number, number] };
export const UV_NOTES: Record<string, Note[]> = {
  'too-yumm': [
    { text: 'LOGO NEVER MOVES', anchor: [0, 0.2, 0.04], proof: [0.3, 0.2] },
    { text: 'COLOUR SORTS THE FLAVOUR', anchor: [0, 0.12, 0.04], proof: [0.62, 0.52] },
    { text: 'ROASTED, NOT FRIED: FIXED SPOT', anchor: [0, 0.05, 0.04], proof: [0.3, 0.8] },
  ],
  mitooshi: [
    { text: 'FILTER, NOT FUNNEL', anchor: [0, 0.16, -0.05], proof: [0.3, 0.3] },
    { text: 'ASCII AS SIGNATURE, NOT GIMMICK', anchor: [0, 0.1, -0.06], proof: [0.6, 0.7] },
  ],
  sook: [
    { text: 'ONE ILLUSTRATED FIGURE PER BLEND', anchor: [0, 0.09, 0.04], proof: [0.3, 0.25] },
    { text: "TONES FROM THE TEA'S ORIGIN", anchor: [0, 0.04, 0.04], proof: [0.6, 0.75] },
  ],
  'house-of-hex': [
    { text: 'WORK LEADS, SITE STEPS BACK', anchor: [0, 0.12, 0.02], proof: [0.3, 0.3] },
    { text: 'THE FAQ DOES THE SALES CALL', anchor: [0, 0.07, 0.02], proof: [0.6, 0.7] },
  ],
  sonde: [
    { text: 'VIOLET = SONDE ACTING', anchor: [0, 0.13, 0.02], proof: [0.3, 0.3] },
    { text: 'AMBER = DRIFT · GREEN = RESOLVED', anchor: [0, 0.08, 0.03], proof: [0.6, 0.72] },
  ],
  'bengal-t20': [
    { text: 'PATTACHITRA · ALPANA · GOMIRA', anchor: [0, 0.05, 0.06], proof: [0.3, 0.3] },
    { text: 'MOTIFS, NOT ONE FIXED MARK', anchor: [0, 0.03, 0.08], proof: [0.6, 0.72] },
  ],
  'jsw-sports': [
    { text: 'CHAPTERS, NOT A RUN OF PAGES', anchor: [0.08, 0.16, 0.02], proof: [0.3, 0.3] },
    { text: 'HINDI-ENGLISH PULL-QUOTES', anchor: [0.08, 0.1, 0.02], proof: [0.65, 0.7] },
  ],
  shunya: [
    { text: 'ONE EMBER SQUARE: THE ONE YOU LIGHT', anchor: [0, 0.07, 0.05], proof: [0.3, 0.3] },
    { text: 'THE WORDMARK THINS TO VAPOUR', anchor: [0, 0.03, 0.05], proof: [0.6, 0.72] },
  ],
  'indo-thai': [
    { text: 'MOTION BEFORE COPY', anchor: [0, 0.16, -0.05], proof: [0.3, 0.3] },
    { text: 'REAL ROSTER, NO STOCK PHOTOS', anchor: [0, 0.1, -0.06], proof: [0.6, 0.72] },
  ],
};

/** Applies every correction to a project after the import overlay. */
export function correct(w: Work): Work {
  const slug = w.slug;
  return {
    ...w,
    title: fixText(w.title),
    description: w.description?.map(fixText),
    sections: w.sections?.map((s) => ({ heading: s.heading, body: s.body.map(fixText) })),
    disciplines: DISCIPLINES[slug] ?? w.disciplines,
    clientType: CLIENT_TYPE[slug] ?? w.clientType,
    year: YEAR[slug] ?? w.year,
    links: LINKS[slug] ? [LINKS[slug]] : [],
    live: undefined,
    uvNotes: UV_NOTES[slug] ?? [],
    deliverables: w.deliverables.map((d) => ({ ...d, alt: fixText(d.alt) })),
  };
}
