// Generated by tools/import-framer.mjs from the live Framer site. Copy is imported as-is.
// Empty until the importer can reach www.visheshmahendru.com + framerusercontent.com.
export const imported: Record<string, Record<string, unknown>> = {};
