// Generated by tools/import-framer.mjs from the live Framer site. Copy is imported as-is.
// Re-run the importer to refresh; edit the per-project files for anything hand-written.
export const imported: Record<string, unknown> = {
  "too-yumm": {
    "title": "TOO YUMM",
    "year": 2024,
    "role": "Packaging Designer, 3D Visualization",
    "clientType": "Studio",
    "scope": "PACKAGING DESIGN, 3D RENDERING",
    "description": [
      "Packaging and 3D visualization for Too Yumm's new flavored nuts line, extending an established mass-market brand into a category that runs on cluttered shelves and repetitive visual language.\n\nDesigned while working at The Graphē in Kolkata, with creative input from the team there. The line needed to feel unmistakably Too Yumm while giving each new flavor its own distinct shelf identity, balancing a \"Roasted, Not Fried\" health claim against the brand's youth-facing, high-energy tone."
    ],
    "sections": [
      {
        "heading": "ONE BRAND, MANY SHELVES",
        "body": [
          "Flavored nuts is a crowded category, and most of that clutter comes from packaging that's fighting for attention rather than communicating anything specific. Too Yumm needed a new range in that same space, but couldn't afford to look like it was just adding to the noise. The brand already had an established identity in market, built on a fun, mass-appeal tone, so the new line had to read as an extension of that system, not a departure from it. Anyone who already knew Too Yumm needed to recognize this as the same brand the moment they saw it on shelf.\n\nAt the same time, the product itself carried a specific claim worth building around: roasted, not fried. That's a genuine point of difference in a category where most snacking nuts lean on flavor alone and say nothing about how they're made. The brief was to give that claim real visual weight without turning the packaging serious or clinical, the kind of shift that would alienate the audience the brand had already built. Every flavor also needed to stand on its own, since a range that looks identical variant to variant loses the ability to signal \"which one do I want\" at a glance, which matters more in this category than almost any other packaging decision."
        ]
      },
      {
        "heading": "COLOR AS SYSTEM",
        "body": [
          "The approach was to give each flavor its own color identity and hand-drawn illustration, treating the pack less like a static label and more like a small piece of storytelling for whatever's inside, green for the tea-forward flavor, orange for the achari cashews, and so on down the line. That illustration style did double duty: it kept the tone playful and approachable, which is where the brand's existing equity lives, while the color-coding did the actual functional job of letting a shopper sort variants without reading a word of copy.\n\nUnderneath the illustration, the layout followed a fixed hierarchy across every pack: the Too Yumm logo held its position as the anchor so brand recognition never wavered, the \"Roasted, Not Fried\" callout sat in a consistent, legible spot rather than competing for space, and nutritional highlights were placed for a quick scan rather than a full read. That structure is what makes the system scale, new flavors can be added without redesigning the whole pack, they just slot a new color and illustration into a layout that's already proven. Final packs were rendered in Blender and composited in Photoshop to get accurate material behavior and real shelf presence for presentation, rather than relying on flat mockups that wouldn't hold up next to the physical product."
        ]
      }
    ],
    "deliverables": [
      {
        "type": "image",
        "src": "/work/too-yumm/01.webp",
        "alt": "Two Too Yumm flavored peanut pouches, Thai sweet chilli in red and Peri Peri in orange, standing against a cream background.",
        "source": "https://framerusercontent.com/images/uoal01j88pTv4gp9cfAPDzYsGfk.png",
        "width": 2385,
        "height": 1500
      },
      {
        "type": "image",
        "src": "/work/too-yumm/02.webp",
        "alt": "Three Too Yumm pouches fanned out: coffee almonds in peach, achaari cashews in green and salted cashews in aqua.",
        "source": "https://framerusercontent.com/images/iCxNNLWR0ZT6dSESjiDs64mTjqQ.png",
        "width": 2385,
        "height": 1500
      },
      {
        "type": "image",
        "src": "/work/too-yumm/03.webp",
        "alt": "Overhead view of seven Too Yumm pouches in different flavor colors arranged in a circle on a cream surface.",
        "source": "https://framerusercontent.com/images/9Dlcq1faVT5LXKmwrDgnF4FiDU.png",
        "width": 2385,
        "height": 1500
      },
      {
        "type": "image",
        "src": "/work/too-yumm/04.webp",
        "alt": "A row of Too Yumm pouches in red, green, purple, orange, aqua and sage, staggered in depth with the orange Peri Peri peanuts pouch at the front.",
        "source": "https://framerusercontent.com/images/S6lgWv2lspym3PiGJqe422tH5mo.png",
        "width": 2385,
        "height": 1500
      },
      {
        "type": "image",
        "src": "/work/too-yumm/05.webp",
        "alt": "Too Yumm coffee almonds pouch lying on a wooden table with a glass jar of almonds tipped over beside it and a plant leaf in the corner.",
        "source": "https://framerusercontent.com/images/ggXCAK7peHs2dKQnKRV1Z5hDdE8.png",
        "width": 2385,
        "height": 1500
      },
      {
        "type": "image",
        "src": "/work/too-yumm/06.webp",
        "alt": "Two Too Yumm coffee almonds pouches on a dark wooden table with scattered almonds and a glass bowl.",
        "source": "https://framerusercontent.com/images/1ZFLnqhJnk2Kha5xPYKk7q1QXY.png",
        "width": 2385,
        "height": 1500
      }
    ]
  },
  "mitooshi": {
    "title": "MITOOSHI",
    "year": 2026,
    "role": "Web Designer, 3D + ASCII Art Direction",
    "clientType": "Studio",
    "scope": "WEB DESIGN, ART DIRECTION",
    "live": "https://www.mitooshi.com/",
    "description": [
      "Homepage design, 3D visuals, and ASCII art direction for Mitooshi, a private operator network connecting funds, portfolio companies, and operators across the prediction market and Web3 ecosystem. Designed during my internship at BHONG, a Barcelona-based design studio.\n\nThe site needed to read as institutional and exclusive on first load, since most of its traffic would be high-value operators deciding whether to even apply."
    ],
    "sections": [
      {
        "heading": "FILTER, NOT FUNNEL",
        "body": [
          "Most Web3 sites lean on one of two failure modes: generic crypto aesthetics (gradients, glowing orbs, stock 3D coins) or visuals so abstract they say nothing about what the product does. Mitooshi couldn't afford either. It's an operator network, not a retail product, so the site's actual job was closer to gatekeeping than converting: it had to filter for the kind of fund and operator that would take the network seriously, and make the wrong kind of visitor bounce.\n\nThat meant the tone had to carry weight most crypto sites never earn: institutional and exclusive, while staying legible enough that a first-time visitor could tell what Mitooshi actually connects and why it mattered, without wading through jargon-heavy copy to find out."
        ]
      },
      {
        "heading": "PRECISION MEETS TEXTURE",
        "body": [
          "The system was built around a tension between technical precision and organic motion. ASCII art became the hero treatment: a nod to raw code culture that read as more considered than a typical crypto landing page, without tipping into gimmick. 3D elements ran alongside it, giving the brand spatial depth and something tactile to hold onto rather than a flat, templated feel.\n\nI worked through the homepage design explorations that set the visual tone and layout hierarchy, built the 3D renders used across the site, and developed the ASCII art direction that ended up as the site's signature element. Everything fed back into the same brief: institutional weight, without sacrificing clarity."
        ]
      }
    ],
    "deliverables": [
      {
        "type": "image",
        "src": "/work/mitooshi/01.webp",
        "alt": "Mitooshi homepage on a laptop screen against a blue studio backdrop, with the headline Strategic Infrastructure for Industry Leaders.",
        "source": "https://framerusercontent.com/images/94lSj3YNa0MsDpjKTvelimnuo0.png",
        "width": 2385,
        "height": 1500
      },
      {
        "type": "image",
        "src": "/work/mitooshi/02.webp",
        "alt": "Mitooshi website shown on a tablet on a dark background, with stat cards reading $4B+, 28%, 88, 930M+, 33 and 27.",
        "source": "https://framerusercontent.com/images/1NbiiJkIzdz4E01TH6Ejnnvpww.png",
        "width": 2385,
        "height": 1500
      },
      {
        "type": "video",
        "src": "/work/mitooshi/03.mp4",
        "alt": "TBC",
        "source": "https://framerusercontent.com/assets/jc55ZHsn3bSDyvL9fiTrjWp3Epw.mp4",
        "width": 1920,
        "height": 1200,
        "poster": "/work/mitooshi/03-poster.webp"
      },
      {
        "type": "image",
        "src": "/work/mitooshi/04.webp",
        "alt": "Dithered dot pattern globe in white on a bright blue square, part of the Mitooshi ASCII style visuals.",
        "source": "https://framerusercontent.com/images/sHXbDiPMzn5FgbSifh9I6U4XvOg.jpg",
        "width": 1080,
        "height": 1080
      },
      {
        "type": "video",
        "src": "/work/mitooshi/05.mp4",
        "alt": "TBC",
        "source": "https://framerusercontent.com/assets/jbMdS64t3KY0rHlruevvZQbj43s.mp4",
        "width": 1920,
        "height": 1920,
        "poster": "/work/mitooshi/05-poster.webp"
      },
      {
        "type": "image",
        "src": "/work/mitooshi/06.webp",
        "alt": "Scattered white dot pattern shapes on a bright blue square, an ASCII style graphic from the Mitooshi visuals.",
        "source": "https://framerusercontent.com/images/Hy1jBizPfzMOK5Zbcm2dDAV9N2w.jpg",
        "width": 1080,
        "height": 1080
      },
      {
        "type": "video",
        "src": "/work/mitooshi/07.mp4",
        "alt": "TBC",
        "source": "https://framerusercontent.com/assets/NL3wgtGIFpCop1GyVdZmmk9lU4.mp4",
        "width": 1920,
        "height": 1920,
        "poster": "/work/mitooshi/07-poster.webp"
      }
    ]
  },
  "sook": {
    "title": "SOOK",
    "year": 2023,
    "role": "Packaging Designer, 3D Visualization",
    "clientType": "Studio",
    "scope": "PACKAGING DESIGN, BRANDING",
    "description": [
      "Packaging design for SOOK, an organic tea brand built on authenticity, wellness, and quiet luxury. The branding system blends minimal illustration, natural tones, and a touch of modern charm.\n\nDesigned while working at The Graphē in Kolkata, with team collaboration and feedback throughout. The brief was to make SOOK feel premium without losing warmth, in a category that usually picks one or the other."
    ],
    "sections": [
      {
        "heading": "PREMIUM, STILL WARM",
        "body": [
          "Organic tea packaging tends to collapse into one of two clichés: overcorrect into opulence and lose the \"organic\" claim entirely, or overcorrect into earthiness and end up looking like every other eco-minimalist shelf brand. SOOK needed to sit between those, premium enough to justify its price point, warm enough to still feel personal and human rather than clinical.\n\nThe harder problem was tone. Most sustainability-driven packaging shouts about it, leaning on visible eco-iconography and heavy-handed messaging. SOOK's brand was closer to the opposite: visual storytelling that communicates mindfulness without overdesign, packaging that whispers calm rather than announcing it."
        ]
      },
      {
        "heading": "QUIET STORYTELLING",
        "body": [
          "The approach centered on quiet storytelling, minimal design with a human presence at its core. Each variant carries its own female illustration paired with a muted, natural tone, greens, reds, browns, drawn from the tea's own origins, so the color itself does emotional work rather than just decorating the pack. The illustration style stayed gentle and editorial, closer to hand-finished than mass-produced.\n\nEach variant was built to stand on its own while still reading as one system, so the range could grow without losing cohesion. I built out 3D mockups in Blender to check shelf consistency and proportions, and pushed for soft, material-accurate light renders over flat mockups, so the final presentation matched SOOK's tone: calm, clean, and modern, an identity that feels serene rather than shouted."
        ]
      }
    ],
    "deliverables": [
      {
        "type": "image",
        "src": "/work/sook/01.webp",
        "alt": "Five SOOK tea boxes in white, aqua, red and gold floating at different angles against a warm beige background.",
        "source": "https://framerusercontent.com/images/gUwhwJCChe2DoaRuWlRyDYB8g.png",
        "width": 2385,
        "height": 1500
      },
      {
        "type": "image",
        "src": "/work/sook/02.webp",
        "alt": "A group of SOOK tea boxes in aqua, white, red and gold standing on a beige surface, each with an illustrated girl on the front.",
        "source": "https://framerusercontent.com/images/2gjz0KoqFAnwfMKSBv3TkSNMw.png",
        "width": 2385,
        "height": 1500
      },
      {
        "type": "image",
        "src": "/work/sook/03.webp",
        "alt": "SOOK tea boxes stacked in a pyramid, showing the illustrated fronts and the back panels with tea details and barcodes.",
        "source": "https://framerusercontent.com/images/V0a5JyPI8HTTXa0mEyWroEkUtc.png",
        "width": 2385,
        "height": 1500
      },
      {
        "type": "image",
        "src": "/work/sook/04.webp",
        "alt": "A green SOOK Garden Fresh Green Tea pouch standing against a beige wall, with an illustrated girl carrying a plant.",
        "source": "https://framerusercontent.com/images/vFK6AnEYJvyUFasRZvsHEr058Q.png",
        "width": 2385,
        "height": 1500
      },
      {
        "type": "image",
        "src": "/work/sook/05.webp",
        "alt": "Close up of SOOK boxes tiled together, showing the aqua Berry Bloom herbal tea panels and the white Summer Sun black tea panels.",
        "source": "https://framerusercontent.com/images/FIT3TpJDrXzxaMCx3xXBFIQVWg.png",
        "width": 2385,
        "height": 1500
      },
      {
        "type": "image",
        "src": "/work/sook/06.webp",
        "alt": "A teal SOOK Berry Bloom tea box on a white block beside a matching tea sachet and a white cup with a tea bag on a saucer.",
        "source": "https://framerusercontent.com/images/cUvOnRGl9EQArEuQlSYKEuWKFXA.png",
        "width": 2385,
        "height": 1500
      }
    ]
  },
  "house-of-hex": {
    "title": "HOUSE OF HEX",
    "year": 2025,
    "role": "Web Designer, Framer Build",
    "clientType": "Freelance",
    "scope": "WEB DESIGN, ART DIRECTION",
    "live": "https://www.houseofhex.design/",
    "description": [
      "Complete website design for House of Hex, a brand and identity design studio, built to house a growing roster of heavyweight client work that, until this project, had nowhere online to live.\n\nDesigned the full site end to end as a visual designer at the studio. This was a website project, not a branding one, the studio's identity work came from elsewhere on the team."
    ],
    "sections": [
      {
        "heading": "NO HOME FOR THE WORK",
        "body": [
          "House of Hex had serious client work behind it, brand and visual identity systems for names like the Bengal Pro T20 League and JSW Sports, but no site of its own. There was no formal brief in the usual sense: the problem was simply that a studio doing sharp, considered work for other people had nothing that sharp or considered representing itself.\n\nThe harder problem is the one every design studio site runs into: the category is saturated with the same moves, bold type, hover reveals, a masonry grid of thumbnails, so it's easy to build something competent and forgettable. The site needed to hold heavyweight case studies without flattening them into generic portfolio tiles, and needed to read as credible to the kind of client that was actually going to hire the studio, not just other designers scrolling for inspiration."
        ]
      },
      {
        "heading": "LETTING WORK LEAD",
        "body": [
          "The structure leans on a grid-driven portfolio landing page that gets out of the way fast, restrained typography, generous whitespace, so each project thumbnail can carry its own visual weight instead of competing with the site's own design for attention. Project pages were built to flex around each case study's actual visual language rather than forcing every project into one identical layout.\n\nBeyond the portfolio itself, the site carries a process section and an FAQ that do real work: they answer the practical questions a prospective client has before reaching out, scope, timeline, how the studio works, rather than leaving that conversation entirely to a contact form. The result is a site that functions as a working sales tool for the studio, not just a gallery."
        ]
      }
    ],
    "deliverables": [
      {
        "type": "video",
        "src": "/work/house-of-hex/01.mp4",
        "alt": "TBC",
        "source": "https://framerusercontent.com/assets/u6ZzY557ntGb2hYZVqfBico2qY.mp4",
        "width": 1920,
        "height": 1200,
        "poster": "/work/house-of-hex/01-poster.webp"
      },
      {
        "type": "image",
        "src": "/work/house-of-hex/02.webp",
        "alt": "House of Hex website contact page open on a laptop on a ridged dark surface with an orange backdrop.",
        "source": "https://framerusercontent.com/images/vxZ1bnzbipXjTZhUWXd9mE4nnQc.png",
        "width": 2385,
        "height": 1500
      },
      {
        "type": "image",
        "src": "/work/house-of-hex/03.webp",
        "alt": "Two phones showing the House of Hex mobile site, an FAQ page and a services page, lying on a dark ridged surface.",
        "source": "https://framerusercontent.com/images/KsAEEFmhLS8aydMcj2hAg0sLik.png",
        "width": 2385,
        "height": 1500
      },
      {
        "type": "image",
        "src": "/work/house-of-hex/04.webp",
        "alt": "House of Hex design system sheet showing typography, colour palette, buttons, components and spacing.",
        "source": "https://framerusercontent.com/images/IdLhTusjoQcGMDY0xgo8dOpGA.png",
        "width": 2400,
        "height": 1500
      }
    ]
  },
  "sonde": {
    "title": "SONDE",
    "year": 2026,
    "role": "Product Designer (Solo)",
    "clientType": "Self-initiated",
    "scope": "PRODUCT DESIGN, UI/UX, FULL CASE STUDY",
    "description": [
      "Sonde is a self-initiated product concept for franchise brand teams. It reads everything a location publishes, rescues off-brand posts with the owner's consent, and turns repeat drift into the templates HQ is missing.\n\nSolo project: research, product strategy, UX, UI, design system, brand, motion and 3D. Three surfaces: an HQ web app, an owner iOS app and a no-login link for the print shop."
    ],
    "sections": [
      {
        "heading": "THE PROBLEM",
        "body": [
          "A franchise brand team can approve every template and still lose control of the brand. Owners of individual locations post what they need, when they need it, and most of it never passes through HQ. Sonde starts from a different reading: when a location posts something off-brand, it is rarely disobedience. It is demand for something HQ has not provided."
        ]
      },
      {
        "heading": "THE PRODUCT",
        "body": [
          "Sonde reads everything each location publishes, flags drift, and shows HQ where it clusters. Instead of blocking the owner, it offers to rescue the post: rebuild it on brand, with the owner's consent, in their own words. Repeat drift becomes a signal for which templates HQ should build next. The loop is detect, rescue, learn.\n\nAn HQ web app for the brand team: the network wall, drift detection and the inspector. An iOS app for the owner: the rescue flow, built to take seconds, not a ticket. A no-login link for the print shop: the final file, verified against the brand, with nothing to sign into.\n\nOne design system across all three surfaces. Violet marks only where Sonde is looking or acting. Amber means drift. Green means resolved. The scan line is always horizontal. Type is Geist and Geist Mono.\n\nNorthline Fitness, its studios and everyone shown are fictional. Photography from Unsplash, with screens composited by me. Survey figures come from secondary research. Pilot numbers are illustrative targets, not results."
        ]
      }
    ],
    "deliverables": [
      {
        "type": "image",
        "src": "/work/sonde/01.webp",
        "alt": "Sonde research board: 84% of franchisors found locations using off-brand content, 42% of confident franchisors still find it frequently, and a breakdown of where a Northline studio's local posts get made, with two illustrative quotes.",
        "source": "https://framerusercontent.com/images/xqipCkYkAtQ4de8FnMmU2k4fn4.png",
        "width": 2400,
        "height": 1510
      },
      {
        "type": "image",
        "src": "/work/sonde/02.webp",
        "alt": "Sonde reframe slide on a dark background: off-brand isn't disobedience, it's demand, followed by five findings about drift, speed, local intent, missing HQ feedback and the sign shop.",
        "source": "https://framerusercontent.com/images/xiQYP0HasLeG3cUymYMv7lf9Xvs.png",
        "width": 2400,
        "height": 1510
      },
      {
        "type": "image",
        "src": "/work/sonde/03.webp",
        "alt": "Sonde core loop diagram with lanes for studio owner, Sonde, brand HQ and print shop, showing how a post is scored, rescued, kept as a signal and clustered into a template need.",
        "source": "https://framerusercontent.com/images/keVeEDGpezX1hTEWuR9YOezqqg.png",
        "width": 2400,
        "height": 1500
      },
      {
        "type": "image",
        "src": "/work/sonde/04.webp",
        "alt": "Exploded layer diagram of a rebuilt Northline Fitness post, 'Teachers train free, all August', with callouts for what was kept and what was rebuilt.",
        "source": "https://framerusercontent.com/images/ZHD8zsLseLrrmw7IvJ2WNVvh9Jk.png",
        "width": 2400,
        "height": 1510
      },
      {
        "type": "image",
        "src": "/work/sonde/05.webp",
        "alt": "Four iOS screens of the Sonde owner app: a lock screen push, the rescued post compared with the original, the swapped-on-Instagram confirmation, and the home screen.",
        "source": "https://framerusercontent.com/images/RGVPPiLdOKZGRPWuLOk5pLrW4.png",
        "width": 2400,
        "height": 1510
      },
      {
        "type": "image",
        "src": "/work/sonde/06.webp",
        "alt": "Sonde pilot targets slide: four illustrative metrics for a 90 day pilot, plus what to test first and the risks to name.",
        "source": "https://framerusercontent.com/images/jLc5HArIOpyijPBql8SZFrqP4.png",
        "width": 2400,
        "height": 1510
      }
    ]
  },
  "indo-thai": {
    "title": "INDO THAI",
    "year": 2024,
    "role": "Web Designer, 3D Visualization",
    "clientType": "Studio",
    "scope": "WEB DESIGN, 3D RENDERING",
    "live": "https://www.indothai.in/",
    "description": [
      "Website design and a 3D hero animation for IndoThai, a ground-handling operator serving airlines and airports across northern India, replacing a dated site with something that actually looked like the scale of the operation behind it.\n\nDesigned and rendered while working at The Graphē in Kolkata. The brief was to modernize the site for an established company, not introduce a new brand."
    ],
    "sections": [
      {
        "heading": "MAKING SCALE VISIBLE",
        "body": [
          "IndoThai has been running since 2010 and holds the Airport Authority of India's ground-handling concession across several northern-region airports, real infrastructure, real airline clients, a genuinely large operation. None of that showed up on the old site, which read like a static company brochure from a decade earlier and did nothing to signal the scale or precision the business actually runs on.\n\nGround handling is also an inherently invisible industry: ramp services, load control, station management, none of it is something the public sees or has a mental image of. The challenge was making a technical, largely unseen operation feel credible and sophisticated on screen, without falling back on generic corporate stock photography that could describe any logistics company."
        ]
      },
      {
        "heading": "MOTION BEFORE COPY",
        "body": [
          "The hero opens on a full 3D render of ground operations that plays out as the visitor scrolls, aircraft, ground vehicles, the choreography of a turnaround, before transitioning into the rest of the site. It's built to do in a few seconds of motion what a paragraph of copy couldn't: signal scale, precision, and safety before the visitor reads a single word.\n\nThe rest of the site is organized around IndoThai's actual service catalog, ramp services, load control, passenger services, station management, and its real airline and airport roster, including Akasa Air and airports from Varanasi to Kolkata, so the credibility comes from specificity rather than claims."
        ]
      }
    ],
    "deliverables": [
      {
        "type": "video",
        "src": "/work/indo-thai/01.mp4",
        "alt": "TBC",
        "source": "https://framerusercontent.com/assets/h3ZDz8jfxemCOthedYoOxpKYw.mp4",
        "width": 1920,
        "height": 1200,
        "poster": "/work/indo-thai/01-poster.webp"
      },
      {
        "type": "image",
        "src": "/work/indo-thai/02.webp",
        "alt": "Two phones showing the Indo Thai website, with the contact page open, on lilac ridged steps.",
        "source": "https://framerusercontent.com/images/sNvRbmvFbx3bXWaRgQZXV1bOiec.png",
        "width": 2385,
        "height": 1500
      },
      {
        "type": "image",
        "src": "/work/indo-thai/03.webp",
        "alt": "Two phones showing Indo Thai website pages for airlines and services, lying on lilac ridged steps.",
        "source": "https://framerusercontent.com/images/fS1KTKmQfXbXyGMlOHJBx4j8R2M.png",
        "width": 2385,
        "height": 1500
      },
      {
        "type": "image",
        "src": "/work/indo-thai/04.webp",
        "alt": "Indo Thai design system sheet showing typography, colour palette, buttons, components and spacing.",
        "source": "https://framerusercontent.com/images/xZa5WFm41uOg3T7XFDmKkGO4xaM.png",
        "width": 2400,
        "height": 1500
      }
    ]
  },
  "bengal-t20": {
    "title": "BENGAL T20 LEAGUE",
    "year": 2026,
    "role": "Brand Designer, Identity + Rollout",
    "clientType": "Agency",
    "scope": "BRAND IDENTITY, ART DIRECTION",
    "description": [
      "Brand identity for the Bengal Pro T20 League, a new regional cricket franchise league that needed to feel unmistakably of Bengal rather than a copy of existing global cricket branding.\n\nWorked on this as part of the team at House of Hex. The system had to hold up across stadium signage, broadcast, merchandise, and city-wide activations, not just a logo on a screen."
    ],
    "sections": [
      {
        "heading": "BEYOND THE CLICHÉ",
        "body": [
          "Regional T20 leagues have multiplied fast since the IPL's success, and most of their branding borrows the same visual shorthand: bold slab type, a generic tiger or lion mascot, a color palette lifted from whichever global franchise did it first. The Bengal Pro T20 League risked becoming one more entry in that pile if the identity leaned on cricket-branding cliché instead of anything specific to Bengal itself.\n\nThe system also had to survive contact with reality, stadium wraps, broadcast graphics, merchandise, city activations, each with different constraints and different audiences, without the identity falling apart or feeling stitched together from separate one-off designs."
        ]
      },
      {
        "heading": "BUILT FROM BENGAL",
        "body": [
          "Rather than referencing other cricket leagues, the identity was built from Bengal's own visual language: Pattachitra scroll art, alpana floor motifs, the folk-mask tradition of Gomira, and the Royal Bengal Tiger, sourced and treated as design material, not decoration bolted onto a generic mark.\n\nThat gave the system a look that reads as native to Bengal rather than adapted for a cricket league, and, because it was built from a flexible set of motifs rather than a single fixed logo treatment, one that travels cleanly from a stadium-scale wrap down to a single merchandise tag."
        ]
      }
    ],
    "deliverables": [
      {
        "type": "image",
        "src": "/work/bengal-t20/01.webp",
        "alt": "Eden Gardens stadium stands dressed in Bengal T20 League branding, with blue and yellow seating and sponsor banners along the boundary.",
        "source": "https://framerusercontent.com/images/S3phJtaA4mIc5F2nKcQwj2ttYU.png",
        "width": 2385,
        "height": 1500
      },
      {
        "type": "image",
        "src": "/work/bengal-t20/02.webp",
        "alt": "Large Bengal T20 League screen frame at the stadium, with tiger mask artwork on each corner and Bengali text.",
        "source": "https://framerusercontent.com/images/5kSxXnyLiCDx4hV6WPCaasqTDc.png",
        "width": 2385,
        "height": 1500
      },
      {
        "type": "image",
        "src": "/work/bengal-t20/03.webp",
        "alt": "A tiger illustration in the league's folk art style painted on a stadium wall above blue and yellow seats and a Bengal T20 League sign.",
        "source": "https://framerusercontent.com/images/t45xz5QsYjM554y8d4aFa8aXAo.png",
        "width": 2400,
        "height": 1500
      },
      {
        "type": "image",
        "src": "/work/bengal-t20/04.webp",
        "alt": "The Bengal T20 League trophy topped with a tiger head, on a branded plinth in front of rows of blue and yellow stadium seats.",
        "source": "https://framerusercontent.com/images/6Md2L1JAKpZPSrXF43SckZVxUVc.png",
        "width": 2385,
        "height": 1500
      },
      {
        "type": "image",
        "src": "/work/bengal-t20/05.webp",
        "alt": "A man speaking at a branded podium with the trophy in front, against a blue backdrop with illustrated cricket and folk art patterns.",
        "source": "https://framerusercontent.com/images/dzmrIz84PABVHezvikqFs8hFU.png",
        "width": 2385,
        "height": 1500
      },
      {
        "type": "image",
        "src": "/work/bengal-t20/06.webp",
        "alt": "Officials seated at the Bengal Pro T20 League players auction table, with tiger artwork on the blue backdrop behind them.",
        "source": "https://framerusercontent.com/images/o5u5NNU53FnI28t8Yy4bEBDUanQ.png",
        "width": 2385,
        "height": 1500
      }
    ]
  },
  "shunya": {
    "title": "SHUNYA",
    "year": 2026,
    "role": "Brand + Packaging Designer (Solo)",
    "clientType": "Self-initiated",
    "scope": "PACKAGING DESIGN, BRAND IDENTITY",
    "description": [
      "Pure camphor, designed around the one thing it does best: disappear. Packaging, brand identity and 3D for SHUNYA (शून्य, zero).\n\nA self-initiated project. Concept, brand identity, packaging design, 3D and motion, built in Figma and Blender."
    ],
    "sections": [
      {
        "heading": "BUILT TO DISAPPEAR",
        "body": [
          "Camphor sublimates. It goes from solid straight to vapour and burns without leaving ash, which also means a cheap pouch lets it evaporate before you ever use it. SHUNYA (शून्य, zero) is built on that single material truth. The packaging exists to hold something that wants to leave, and the identity shows it leaving."
        ]
      },
      {
        "heading": "LOSING MASS",
        "body": [
          "The wordmark loses weight as the range moves from solid to vapour, with the letters drifting apart as the weight drops. A grid of rounded squares, one per tablet, thins out the same way. One square is printed in ember orange: the tablet you light. It is the only colour in the whole system.\n\nThe range has four pieces: foil-sealed Pooja tablets, Bhimseni crystal in a glass and cork jar, Air diffuser cubes in a tin whose lid is pierced in the grid pattern, and a Ritual Set that holds the full story on one lid. Every pack was built to real dielines and rendered in Blender with debossed grids, raised wordmarks and a copper foil ember."
        ]
      }
    ],
    "deliverables": [
      {
        "type": "video",
        "src": "/work/shunya/01.mp4",
        "alt": "TBC",
        "source": "https://framerusercontent.com/assets/hfjn0LVzYd8XtUzVEwOYSfDm9Kw.mp4",
        "width": 1920,
        "height": 1200,
        "poster": "/work/shunya/01-poster.webp"
      },
      {
        "type": "image",
        "src": "/work/shunya/02.webp",
        "alt": "SHUNYA camphor range on a grey studio background: the white Ritual Set box, a tablet carton, a glass jar with a cork stopper and a round tin, with loose camphor tablets in front.",
        "source": "https://framerusercontent.com/images/tmFI9wK0lpN1A7grnyWPhCYwZY.png",
        "width": 2385,
        "height": 1500
      },
      {
        "type": "image",
        "src": "/work/shunya/03.webp",
        "alt": "SHUNYA tablet carton open to show a foil blister pack, beside a second carton and a strip of ten foil sealed camphor tablets, all marked with a grid of black rounded squares.",
        "source": "https://framerusercontent.com/images/2K0HHR5cOq2uYn7wxAAw2VV1m0s.png",
        "width": 2400,
        "height": 1500
      },
      {
        "type": "image",
        "src": "/work/shunya/04.webp",
        "alt": "Top down view of the SHUNYA Air tin with its lid beside it, the lid printed with a thinning grid of dots and the tin filled with white camphor cubes.",
        "source": "https://framerusercontent.com/images/QNA6Mg3KaFhCALKIZyspDur0Ag.png",
        "width": 2385,
        "height": 1500
      },
      {
        "type": "image",
        "src": "/work/shunya/05.webp",
        "alt": "SHUNYA identity system sheet: the wordmark in Latin and Devanagari thinning from solid to vapour to zero, the matching grid of squares, and the chalk, graphite and ember colour palette.",
        "source": "https://framerusercontent.com/images/uO1ZKefqIlWht6ObKaZbQj76PdA.png",
        "width": 2385,
        "height": 1500
      }
    ]
  },
  "jsw-sports": {
    "title": "JSW SPORTS",
    "year": 2025,
    "role": "Editorial Designer",
    "clientType": "Studio",
    "scope": "EDITORIAL DESIGN, PUBLICATION DESIGN",
    "description": [
      "Editorial design for two JSW Sports publications: a coffee table book for the Haryana Steelers' maiden PKL title, and the Inspire Institute of Sport's 2025 annual report.\n\nWorked on both as part of the team at House of Hex. Neither publication existed in this form before, both were built from the ground up."
    ],
    "sections": [
      {
        "heading": "MORE THAN A SCOREBOARD",
        "body": [
          "Both projects shared the same underlying problem: an elite sports organization whose real story lives almost entirely in match highlights, stats, and press releases, not in anything built to be kept. The Haryana Steelers had just won their first PKL title after seven seasons of building, a story with real texture: rural academies, a co-captaincy experiment, a losing final the year before, that a scoreboard alone couldn't carry. IIS runs a sprawling, genuinely impressive high-performance ecosystem across a dozen Olympic sports, and needed a flagship document that could communicate that scale to partners and sponsors, not just list results.\n\nThe design problem that followed was structural: both publications had to hold dense, long-form editorial content, athlete profiles, coach bios, bilingual quotes, data, across dozens of pages, while staying visually premium enough to function as a physical object people actually keep, a coffee-table book and a boardroom annual report, not a printed PDF."
        ]
      },
      {
        "heading": "STRUCTURE FOR WEIGHT",
        "body": [
          "For the Haryana Steelers book, the layout was built to let raw kabaddi imagery and typographic movement carry the weight, sectioned into distinct chapters like \"Roots of Glory\" and \"Losses, Lessons & the Big Win\" rather than one undifferentiated run of pages, with bilingual Hindi-English pull-quotes from players and coaches kept as a recurring device throughout.\n\nFor the IIS Annual Report, the structure leans on long-form storytelling, athlete comeback narratives, coach profiles, infrastructure deep-dives, given an editorial hierarchy that signals this is the organization's flagship document rather than a routine report, with partner credit built into the layout rather than tacked on as a logo strip at the end."
        ]
      }
    ],
    "deliverables": [
      {
        "type": "image",
        "src": "/work/jsw-sports/01.webp",
        "alt": "Haryana Steelers book cover, Haqq Se Steelers, showing three players with the trophy on a navy and gold cover.",
        "source": "https://framerusercontent.com/images/KAxYJfW0ceC81ikKvuy0FM5eMl8.png",
        "width": 2385,
        "height": 1500
      },
      {
        "type": "image",
        "src": "/work/jsw-sports/02.webp",
        "alt": "Inspire Institute of Sport annual report 2024 2025 cover with a group of athletes in front of a red building, on a teal back cover.",
        "source": "https://framerusercontent.com/images/J4NDvqDhkSdGOGX6EF8WtEhZkko.png",
        "width": 2385,
        "height": 1500
      },
      {
        "type": "image",
        "src": "/work/jsw-sports/03.webp",
        "alt": "Full wraparound cover of the Haryana Steelers book, with a quote on the back and the players and trophy on the front.",
        "source": "https://framerusercontent.com/images/MLk6ybRtGFNkyfydwruH3xPm4.png",
        "width": 2400,
        "height": 1500
      },
      {
        "type": "image",
        "src": "/work/jsw-sports/04.webp",
        "alt": "Full wraparound cover of the Inspire Institute of Sport annual report, with the logo on the teal back and athletes on the front.",
        "source": "https://framerusercontent.com/images/Ve7eJq5FOfuCj1deltYsU0bheM.png",
        "width": 2385,
        "height": 1500
      },
      {
        "type": "image",
        "src": "/work/jsw-sports/05.webp",
        "alt": "Four spreads from the Haryana Steelers book: Foreword, The Early Years, A Strategic Shift and The Semi-Final.",
        "source": "https://framerusercontent.com/images/ARH9e0wQb2OFMSqsxUHNMNYo0g.png",
        "width": 2385,
        "height": 1500
      },
      {
        "type": "image",
        "src": "/work/jsw-sports/06.webp",
        "alt": "Four spreads from the Inspire Institute of Sport annual report in orange, green and teal, with athlete photos and statistics such as 22%.",
        "source": "https://framerusercontent.com/images/hLZpoUBTOhTLTiaiFTjdlUL58CY.png",
        "width": 2385,
        "height": 1500
      }
    ]
  },
  "__archive": [
    {
      "type": "image",
      "alt": "Duotone cyan collage of two faces in profile behind a bright cyan shape, with blurred flowers on the left.",
      "src": "/archive/01.webp",
      "width": 1600,
      "height": 1600,
      "source": "https://framerusercontent.com/images/7p10XVUO63PDFZTCIsds47LY.png"
    },
    {
      "type": "image",
      "alt": "Red and black halftone poster with large distressed lettering reading 2FAST over a blurred crowd scene.",
      "src": "/archive/02.webp",
      "width": 1600,
      "height": 1600,
      "source": "https://framerusercontent.com/images/HLv1YeGCJGh5ckEATODuvq1vAck.png"
    },
    {
      "type": "image",
      "alt": "Pink CD case lying open on a pink surface, showing a disc with an illustrated figure and handwritten lettering.",
      "src": "/archive/03.webp",
      "width": 1280,
      "height": 1600,
      "source": "https://framerusercontent.com/images/Wmpc6OdQu5ZsbLQMa820IoiFRk.png"
    },
    {
      "type": "image",
      "alt": "Pink poster with handwritten lettering reading amnesia, an illustrated figure holding their head, and a handwritten list down the left side.",
      "src": "/archive/04.webp",
      "width": 1280,
      "height": 1600,
      "source": "https://framerusercontent.com/images/VcRh5JW4hVUDziwteirW4Oq7xQA.png"
    },
    {
      "type": "image",
      "alt": "Surreal landscape with three tall pillars in purple, yellow and pink rising from shallow water, with a lone figure standing between them under a cloudy sky.",
      "src": "/archive/05.webp",
      "width": 1080,
      "height": 1241,
      "source": "https://framerusercontent.com/images/8FcYHpeZgJ5orMSXaDAochqQ3Vw.png"
    },
    {
      "type": "image",
      "alt": "3D render of an empty attic classroom with wooden desks, stone walls and sunlight through tall leaded windows.",
      "src": "/archive/06.webp",
      "width": 1600,
      "height": 900,
      "source": "https://framerusercontent.com/images/EG1rurql30AhYLYOdam7xipW6s.png"
    },
    {
      "type": "image",
      "alt": "3D render of a wooden side table against a stone wall holding glass bottles and jars, with a stack of books in the foreground.",
      "src": "/archive/07.webp",
      "width": 1600,
      "height": 900,
      "source": "https://framerusercontent.com/images/owhmKiFnD9FTRvmz1J0aN7pqhY.png"
    },
    {
      "type": "image",
      "alt": "3D render close-up of a sunlit wooden desk with open books, a quill, a scroll and a candle.",
      "src": "/archive/08.webp",
      "width": 1600,
      "height": 900,
      "source": "https://framerusercontent.com/images/z0g8edGS81m69wCy9SVxfmzKp8.png"
    },
    {
      "type": "image",
      "alt": "3D render of classroom desks with an open book and a quill, a white owl on a perch and a chalkboard behind.",
      "src": "/archive/09.webp",
      "width": 1600,
      "height": 900,
      "source": "https://framerusercontent.com/images/sxjU5BPTH5S9OI2FfqdH2X1wC0.png"
    },
    {
      "type": "image",
      "alt": "3D render of rows of wooden desks and benches beside tall leaded windows, with glassware on a side table.",
      "src": "/archive/10.webp",
      "width": 1600,
      "height": 900,
      "source": "https://framerusercontent.com/images/X3XDz4Zj4srvzmU5MvWXquuruU.png"
    },
    {
      "type": "image",
      "alt": "3D render looking down a classroom aisle between wooden desks toward a lectern, a hanging banner and a chalkboard.",
      "src": "/archive/11.webp",
      "width": 1600,
      "height": 900,
      "source": "https://framerusercontent.com/images/vBdE3BPjOZ5S2leZ5Iw0Xi4XU0.png"
    },
    {
      "type": "image",
      "alt": "3D render of a classroom seen from above, with an iron chandelier in the foreground and sunlight falling across the desks.",
      "src": "/archive/12.webp",
      "width": 1600,
      "height": 900,
      "source": "https://framerusercontent.com/images/I8QS4vhJpHm11QPSbBCUsn6nqg.png"
    },
    {
      "type": "image",
      "alt": "Top-down view of an orange sports car driving on an asphalt road that turns into orange sand dunes ahead.",
      "src": "/archive/13.webp",
      "width": 1600,
      "height": 1599,
      "source": "https://framerusercontent.com/images/zveR8zaS7a927k5zZOFimSS260.png"
    },
    {
      "type": "image",
      "alt": "3D render of a black alloy wheel with a yellow brake caliper and a Michelin Pilot Sport Cup 2 tyre, in black and white surroundings.",
      "src": "/archive/14.webp",
      "width": 1599,
      "height": 1600,
      "source": "https://framerusercontent.com/images/mPp0hT1UTg0JGcVCrQDRqYO9PE.png"
    },
    {
      "type": "image",
      "alt": "Close-up of a Mercedes-Benz badge on an orange car body, with soft light and a blurred background.",
      "src": "/archive/15.webp",
      "width": 1600,
      "height": 1600,
      "source": "https://framerusercontent.com/images/bhityejAJ4JGtiq2eVjWdOqi48.png"
    },
    {
      "type": "image",
      "alt": "Top-down view of an orange sports car parked on a flat white surface.",
      "src": "/archive/16.webp",
      "width": 1600,
      "height": 1600,
      "source": "https://framerusercontent.com/images/vetIl0Iu8FuZVgczJ6tg7MkyU.png"
    },
    {
      "type": "image",
      "alt": "3D render of an orange Mercedes-AMG coupe in a bright concrete room with sheer curtains and a wooden floor.",
      "src": "/archive/17.webp",
      "width": 1600,
      "height": 1600,
      "source": "https://framerusercontent.com/images/R2Aald3Ffb9huwEZEFJfW7z4gs.png"
    },
    {
      "type": "image",
      "alt": "Grey sports car seen from behind with a large rear wing and a lit taillight bar, parked on wet gravel at dusk.",
      "src": "/archive/18.webp",
      "width": 1600,
      "height": 900,
      "source": "https://framerusercontent.com/images/SUqXrfR9JPNnjyMvEJAQBTnweYQ.png"
    },
    {
      "type": "image",
      "alt": "Close-up of a black wheel with a red brake caliper and a GT3 centre cap, in dim light.",
      "src": "/archive/19.webp",
      "width": 1600,
      "height": 900,
      "source": "https://framerusercontent.com/images/K0OZwul6vfG8qzI32KGy3QvtPuY.png"
    },
    {
      "type": "image",
      "alt": "Rear view of a grey sports car with a large wing and a glowing red taillight bar in a dark industrial garage.",
      "src": "/archive/20.webp",
      "width": 1600,
      "height": 900,
      "source": "https://framerusercontent.com/images/57yGnad7KesjXH1qrF0kubH3GtQ.png"
    },
    {
      "type": "image",
      "alt": "Close-up of a dark wheel with a red brake caliper and a GT3 centre cap, lit from one side.",
      "src": "/archive/21.webp",
      "width": 1600,
      "height": 900,
      "source": "https://framerusercontent.com/images/SoaRL7F6Vkl7dF977XyNfsm7N5o.png"
    },
    {
      "type": "image",
      "alt": "Dark garage with the rear wheel arch of a grey car in the foreground and a silver coupe blurred behind it.",
      "src": "/archive/22.webp",
      "width": 1600,
      "height": 900,
      "source": "https://framerusercontent.com/images/WO8ugAPwiqooX49UM3M4a6LvOU.png"
    },
    {
      "type": "image",
      "alt": "Grey sports car with a glowing red taillight bar in a dark garage, with a silver coupe parked behind it.",
      "src": "/archive/23.webp",
      "width": 1600,
      "height": 900,
      "source": "https://framerusercontent.com/images/H0GA5kt3lqARS2efAIw80NUtc.png"
    },
    {
      "type": "image",
      "alt": "Dark grey sports car seen from above and behind in a garage, beside a white sedan and a beam of light.",
      "src": "/archive/24.webp",
      "width": 1600,
      "height": 900,
      "source": "https://framerusercontent.com/images/IknHo3geyNPFtOFc3H4RaUGuo.png"
    },
    {
      "type": "image",
      "alt": "Ten ceramic vases and cups in grey, white, black, blue and terracotta glazes floating on a grey background.",
      "src": "/archive/25.webp",
      "width": 1600,
      "height": 1600,
      "source": "https://framerusercontent.com/images/Rt9x6V4iBJGRw2M9Iy8nvw26PA.png"
    },
    {
      "type": "image",
      "alt": "3D render of a beige retro desktop computer with a CRT monitor showing orange text and a keyboard on a wooden desk.",
      "src": "/archive/26.webp",
      "width": 1481,
      "height": 1600,
      "source": "https://framerusercontent.com/images/lFbVRYhBc1e4CnkSKogez2bBw8.png"
    },
    {
      "type": "image",
      "alt": "Back of a beige retro computer monitor with a pointing-hand sticker, tangled cables and a plant on a wooden floor.",
      "src": "/archive/27.webp",
      "width": 1481,
      "height": 1600,
      "source": "https://framerusercontent.com/images/t2Yl8Iwvv6pEI8DoDo7mC4Qy4tU.png"
    },
    {
      "type": "image",
      "alt": "Retro computer on a wooden desk with floppy disks on top, the screen showing glowing orange lettering reading sudo, and plants in the foreground.",
      "src": "/archive/28.webp",
      "width": 1481,
      "height": 1600,
      "source": "https://framerusercontent.com/images/UT8ecXhL5VGzodx2uoTg9SfOtw.png"
    },
    {
      "type": "image",
      "alt": "Retro computer and keyboard on a wooden desk, with floppy disks stacked on the monitor and orange text on the screen.",
      "src": "/archive/29.webp",
      "width": 1481,
      "height": 1600,
      "source": "https://framerusercontent.com/images/EXyDJhgHwIajkISSWTo9MFlHIc.png"
    },
    {
      "type": "image",
      "alt": "Close-up of a beige IBM computer case and keyboard in soft sunlight.",
      "src": "/archive/30.webp",
      "width": 1481,
      "height": 1600,
      "source": "https://framerusercontent.com/images/upHadQg7WhT9tSp1DzpbIYYlTAo.png"
    },
    {
      "type": "image",
      "alt": "Close-up of a CRT screen showing orange pixel lettering and a full alphabet.",
      "src": "/archive/31.webp",
      "width": 1481,
      "height": 1600,
      "source": "https://framerusercontent.com/images/49uXooEGrtX1BoAAVE0MIIFh4.png"
    },
    {
      "type": "image",
      "alt": "Back of a beige CRT monitor in sunlight, with an orange pointing-hand sticker and cables coiled on a wooden floor.",
      "src": "/archive/32.webp",
      "width": 1481,
      "height": 1600,
      "source": "https://framerusercontent.com/images/2zHHXhwgp8m6Z5soMAr2jvRH4.png"
    },
    {
      "type": "image",
      "alt": "Dark teal scene looking down at hooded figures gathered around a glowing circular platform, with cables hanging from above.",
      "src": "/archive/33.webp",
      "width": 1600,
      "height": 1600,
      "source": "https://framerusercontent.com/images/i6ouBc5VpJyd2KPWNLd2H5ppIRU.png"
    },
    {
      "type": "image",
      "alt": "Poster with the title Love Again in large serif type and script lettering over a collage of a couple in silhouette and young people embracing.",
      "src": "/archive/34.webp",
      "width": 1097,
      "height": 1600,
      "source": "https://framerusercontent.com/images/TYHNijv9c4bRZ1194dydhSVfkLs.png"
    },
    {
      "type": "image",
      "alt": "Black and white poster with bold rounded lettering reading stay away, a dictionary-style definition, and a lone figure standing in a small boat.",
      "src": "/archive/35.webp",
      "width": 1097,
      "height": 1600,
      "source": "https://framerusercontent.com/images/ECZNKVGXNCQgrOqxiMm9kvkiGyY.png"
    },
    {
      "type": "image",
      "alt": "Off-white poster with red type reading we suffer more often in imagination than in reality, around a black illustrated brain.",
      "src": "/archive/36.webp",
      "width": 1097,
      "height": 1600,
      "source": "https://framerusercontent.com/images/l4uTt8TsS1Gzrjw1fBse5TNO9sk.png"
    },
    {
      "type": "image",
      "alt": "Poster of a silhouetted figure standing in a lit doorway in a dark room, with a short quote about heartbreak at the top.",
      "src": "/archive/37.webp",
      "width": 1097,
      "height": 1600,
      "source": "https://framerusercontent.com/images/GTQV5hafLlVVvY0pOihf4EARqdk.png"
    },
    {
      "type": "image",
      "alt": "Grey poster with red blackletter type reading narcissist over three figures in masks and utility clothing.",
      "src": "/archive/38.webp",
      "width": 1080,
      "height": 1080,
      "source": "https://framerusercontent.com/images/1cmeIZb73GEmo2TyzKaD3ghyYb0.png"
    },
    {
      "type": "image",
      "alt": "Red-tinted poster with blackletter type reading narcissist over a photo of two performers on stage in front of a crowd.",
      "src": "/archive/39.webp",
      "width": 1131,
      "height": 1600,
      "source": "https://framerusercontent.com/images/VE8PprZ7iWtIZtJsG0AJ4zTjY.png"
    },
    {
      "type": "image",
      "alt": "White poster with red dashed lines, a classical statue holding a severed head and a sword, and black and red type about an apology.",
      "src": "/archive/40.webp",
      "width": 1067,
      "height": 1600,
      "source": "https://framerusercontent.com/images/0ZDW23vgp4NKY8S6nIghuGyHzE.png"
    },
    {
      "type": "image",
      "alt": "White poster with red dashed lines and a broken classical bust, with type asking how many parts of me to be killed to keep you alive.",
      "src": "/archive/41.webp",
      "width": 1067,
      "height": 1600,
      "source": "https://framerusercontent.com/images/HD5VJE8TSGfUg5dKDYHj4OhP6bc.png"
    },
    {
      "type": "image",
      "alt": "White poster with red dashed lines, a twisting classical figure over a red paper collage, and type reading the word sorry won't fix what you did this time.",
      "src": "/archive/42.webp",
      "width": 1067,
      "height": 1600,
      "source": "https://framerusercontent.com/images/ievX6EOJmoW9jzmKW1PHEay1Ic.png"
    },
    {
      "type": "image",
      "alt": "Black and white portrait with red tape lettering reading Whole Lotta Red and the word Carti across the face, with a parental advisory label.",
      "src": "/archive/43.webp",
      "width": 1599,
      "height": 1600,
      "source": "https://framerusercontent.com/images/sfU5N2sI0cIv0jmUcRMqP6e8Ok.png"
    },
    {
      "type": "image",
      "alt": "Pink halftone image of two figures, one resting on the other's shoulder, with Hindi lettering at top left and the words Roro and Saif at top right.",
      "src": "/archive/44.webp",
      "width": 1600,
      "height": 1600,
      "source": "https://framerusercontent.com/images/qMdhUxVo2JAidSt0bn0b43ck2ao.png"
    },
    {
      "type": "image",
      "alt": "Wide banner of a white spiky blackletter logo over vertical strips of photos showing people in a hallway.",
      "src": "/archive/45.webp",
      "width": 1600,
      "height": 823,
      "source": "https://framerusercontent.com/images/kYaVFvfo5fwORxL6AxFSFvJb58.png"
    },
    {
      "type": "image",
      "alt": "Painted lotus flowers and leaves in coral and dark green over a textured blue and lilac background.",
      "src": "/archive/46.webp",
      "width": 1500,
      "height": 1500,
      "source": "https://framerusercontent.com/images/025ZVlmIa5h0Bal4jlILPmf0XWE.png"
    }
  ]
};
