/**
 * H3: responsive sizes for every case-study image and video poster: AVIF and WebP at 640, 1200,
 * 1800 and 2400 px wide (never wider than the source; the source width is always included when it
 * falls between steps). Source: the AVIF re-encoded from the full-colour master where one exists,
 * else the WebP. Output public/work/<slug>/sized/<name>-<w>.{avif,webp} and content/sizes.ts
 * (image path → widths). Re-run after any image changes.
 */
import sharp from 'sharp';
import { readdirSync, existsSync, mkdirSync, writeFileSync, statSync } from 'fs';
const PUB = new URL('../public/', import.meta.url).pathname;
const OUT = new URL('../content/sizes.ts', import.meta.url).pathname;
const STEPS = [640, 1200, 1800, 2400];
const result = {};
const jobs = [];
for (const slug of readdirSync(PUB + 'work').sort()) {
  const dir = `${PUB}work/${slug}/`;
  if (!statSync(dir).isDirectory()) continue;
  mkdirSync(dir + 'sized', { recursive: true });
  for (const f of readdirSync(dir).sort()) {
    if (!f.endsWith('.webp') || f.includes('-fluor')) continue;
    const name = f.replace('.webp', '');
    const src = existsSync(dir + name + '.avif') ? dir + name + '.avif' : dir + f;
    jobs.push(
      async () => {
        const { width } = await sharp(src).metadata();
        const widths = STEPS.filter((w) => w < width);
        if (!widths.length || widths[widths.length - 1] < width * 0.92) widths.push(Math.min(width, 2400));
        for (const w of widths) {
          const base = `${dir}sized/${name}-${w}`;
          if (!existsSync(base + '.avif')) await sharp(src).resize({ width: w }).avif({ quality: 62, effort: 4 }).toFile(base + '.avif');
          if (!existsSync(base + '.webp')) await sharp(src).resize({ width: w }).webp({ quality: 84 }).toFile(base + '.webp');
        }
        result[`/work/${slug}/${f}`] = widths;
      },
    );
  }
}
// a few at a time: AVIF encoding is CPU-heavy
const pool = 4;
let i = 0;
await Promise.all(Array.from({ length: pool }, async () => { while (i < jobs.length) await jobs[i++](); }));
const keys = Object.keys(result).sort();
writeFileSync(
  OUT,
  `/** Generated by tools/proof-sizes.mjs: the widths available under public/work/<slug>/sized/ for each image. */\nexport const SIZES: Record<string, number[]> = {\n${keys.map((k) => `  ${JSON.stringify(k)}: [${result[k].join(', ')}],`).join('\n')}\n};\n`,
);
console.log(`${keys.length} images → ${keys.reduce((a, k) => a + result[k].length, 0)} sizes × 2 formats`);
